# Agent Sandbox Policy for agentsh + Runloop
# Maximum containment for running AI agent code in Runloop Devboxes

version: 1
name: default
description: |
  High-security sandbox for AI agents running in Runloop Devboxes.
  Protects against malicious AI-generated code, cloud metadata SSRF,
  container escape, and credential leakage.

# =============================================================================
# FILE OPERATION RULES
# =============================================================================

file_rules:
  # ---------------------------------------------------------------------------
  # Workspace - read/write allowed, deletes are soft (recoverable)
  # ---------------------------------------------------------------------------

  - name: allow-workspace-read
    description: Allow reading files in workspace
    paths:
      - "${PROJECT_ROOT}"
      - "${PROJECT_ROOT}/**"
    operations:
      - read
      - open
      - stat
      - list
      - readlink
    decision: allow

  - name: allow-workspace-write
    description: Allow writing files in workspace
    paths:
      - "${PROJECT_ROOT}"
      - "${PROJECT_ROOT}/**"
    operations:
      - write
      - create
      - mkdir
      - chmod
      - rename
    decision: allow

  - name: soft-delete-workspace
    description: Soft-delete files in workspace (recoverable)
    paths:
      - "${PROJECT_ROOT}"
      - "${PROJECT_ROOT}/**"
    operations:
      - delete
      - rmdir
    decision: soft_delete
    message: "File quarantined (recoverable): {{.Path}}"

  # ---------------------------------------------------------------------------
  # Temp directories - sandboxed
  # ---------------------------------------------------------------------------

  - name: allow-tmp
    description: Full access to temp directories
    paths:
      - "/tmp/**"
      - "/var/tmp/**"
    operations:
      - "*"
    decision: allow

  # ---------------------------------------------------------------------------
  # Block dangerous binaries (before system read allow)
  # ---------------------------------------------------------------------------

  - name: block-dangerous-binaries
    description: Block execution of privilege escalation tools
    paths:
      - "/usr/bin/sudo"
      - "/usr/bin/su"
      - "/usr/bin/pkexec"
      - "/usr/bin/doas"
      - "/bin/su"
      - "/usr/sbin/chroot"
      - "/usr/bin/nsenter"
      - "/usr/bin/unshare"
    operations:
      - "*"
    decision: deny
    message: "Access to privilege escalation tool blocked: {{.Path}}"

  # ---------------------------------------------------------------------------
  # Block Docker socket access (container escape prevention)
  # ---------------------------------------------------------------------------

  - name: block-docker-socket
    description: Block Docker socket access to prevent container escape
    paths:
      - "/var/run/docker.sock"
      - "/run/docker.sock"
      - "/var/run/containerd/**"
      - "/run/containerd/**"
    operations:
      - "*"
    decision: deny
    message: "Container runtime access blocked: {{.Path}}"

  # ---------------------------------------------------------------------------
  # System paths - minimal read-only
  # ---------------------------------------------------------------------------

  - name: allow-system-read
    description: Read access to system paths
    paths:
      - "/usr/**"
      - "/lib/**"
      - "/lib64/**"
      - "/bin/**"
      - "/sbin/**"
    operations:
      - read
      - open
      - stat
      - list
      - readlink
    decision: allow

  - name: allow-etc-minimal
    description: Read minimal config files
    paths:
      - "/etc/hosts"
      - "/etc/resolv.conf"
      - "/etc/ssl/certs/**"
      - "/etc/ca-certificates/**"
      - "/etc/localtime"
    operations:
      - read
      - stat
    decision: allow

  # ---------------------------------------------------------------------------
  # APPROVE credential/secret access (not deny - visible decision)
  # ---------------------------------------------------------------------------

  - name: approve-ssh-access
    description: Require approval for SSH key access
    paths:
      - "${HOME}/.ssh/**"
      - "/root/.ssh/**"
    operations:
      - "*"
    decision: approve
    message: "Agent wants to access SSH keys: {{.Path}}"
    timeout: 5m

  - name: approve-aws-credentials
    description: Require approval for AWS credentials
    paths:
      - "${HOME}/.aws/**"
      - "/root/.aws/**"
    operations:
      - "*"
    decision: approve
    message: "Agent wants to access AWS credentials: {{.Path}}"
    timeout: 5m

  - name: approve-cloud-credentials
    description: Require approval for cloud credentials
    paths:
      - "${HOME}/.gcloud/**"
      - "${HOME}/.azure/**"
      - "${HOME}/.config/gcloud/**"
      - "${HOME}/.kube/**"
    operations:
      - "*"
    decision: approve
    message: "Agent wants to access cloud credentials: {{.Path}}"
    timeout: 5m

  - name: approve-env-files
    description: Require approval for .env files
    paths:
      - "**/.env"
      - "**/.env.*"
    operations:
      - "*"
    decision: approve
    message: "Agent wants to access environment file: {{.Path}}"
    timeout: 5m

  - name: approve-git-credentials
    description: Require approval for git credentials
    paths:
      - "${HOME}/.git-credentials"
      - "**/.netrc"
    operations:
      - "*"
    decision: approve
    message: "Agent wants to access git credentials: {{.Path}}"
    timeout: 5m

  # ---------------------------------------------------------------------------
  # Package caches - read-only
  # ---------------------------------------------------------------------------

  - name: allow-cache-read
    description: Read-only cache access
    paths:
      - "${HOME}/.npm/**"
      - "${HOME}/.cache/**"
      - "${HOME}/.cargo/**"
      - "/root/.npm/**"
      - "/root/.cache/**"
      - "/root/.cargo/**"
    operations:
      - read
      - open
      - stat
      - list
    decision: allow

  # ---------------------------------------------------------------------------
  # DENY everything else
  # ---------------------------------------------------------------------------

  - name: deny-proc-sys
    description: Block /proc and /sys (container escape prevention)
    paths:
      - "/proc/**"
      - "/sys/**"
    operations:
      - "*"
    decision: deny

  - name: default-deny-files
    description: Deny all other file operations
    paths:
      - "**"
    operations:
      - "*"
    decision: deny

# =============================================================================
# NETWORK OPERATION RULES
# =============================================================================

network_rules:
  # ---------------------------------------------------------------------------
  # Localhost only by default
  # ---------------------------------------------------------------------------

  - name: allow-localhost
    description: Allow localhost connections
    cidrs:
      - "127.0.0.1/32"
      - "::1/128"
    decision: allow

  # ---------------------------------------------------------------------------
  # Package registries - allowed
  # ---------------------------------------------------------------------------

  - name: allow-npm
    description: npm registry
    domains:
      - "registry.npmjs.org"
    ports: [443]
    decision: allow

  - name: allow-pypi
    description: PyPI
    domains:
      - "pypi.org"
      - "files.pythonhosted.org"
    ports: [443]
    decision: allow

  - name: allow-cargo
    description: Cargo registry
    domains:
      - "crates.io"
      - "static.crates.io"
    ports: [443]
    decision: allow

  - name: allow-go-proxy
    description: Go module proxy
    domains:
      - "proxy.golang.org"
      - "sum.golang.org"
    ports: [443]
    decision: allow

  # ---------------------------------------------------------------------------
  # Embedded LLM Proxy
  # ---------------------------------------------------------------------------

  - name: allow-llm-proxy
    description: Allow connections to embedded LLM proxy on localhost
    cidrs:
      - "127.0.0.1/32"
    decision: allow

  # ---------------------------------------------------------------------------
  # Block cloud metadata services (SSRF protection)
  # ---------------------------------------------------------------------------

  - name: block-cloud-metadata
    description: Block all cloud metadata endpoints (AWS, GCP, Azure, Alibaba)
    cidrs:
      - "169.254.169.254/32"
      - "100.100.100.200/32"
    domains:
      - "metadata.google.internal"
      - "metadata.goog"
    decision: deny
    message: "Cloud metadata access blocked: {{.RemoteAddr}}"

  # ---------------------------------------------------------------------------
  # Block Kubernetes control plane
  # ---------------------------------------------------------------------------

  - name: block-kubernetes
    description: Block Kubernetes API access
    domains:
      - "kubernetes.default.svc"
      - "*.svc.cluster.local"
    decision: deny
    message: "Kubernetes API access blocked: {{.RemoteAddr}}"

  # ---------------------------------------------------------------------------
  # Block private/internal networks (lateral movement prevention)
  # ---------------------------------------------------------------------------

  - name: block-private-networks
    description: Block internal/private networks
    cidrs:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
      - "169.254.0.0/16"
    decision: deny
    message: "Internal network access blocked: {{.RemoteAddr}}"

  # ---------------------------------------------------------------------------
  # Block malicious/untrusted domains
  # ---------------------------------------------------------------------------

  - name: block-evil-domains
    description: Block known malicious domains
    domains:
      - "evil.com"
      - "*.evil.com"
    decision: deny
    message: "Connection to untrusted domain blocked: {{.RemoteAddr}}"

  # ---------------------------------------------------------------------------
  # Require approval for all other destinations
  # ---------------------------------------------------------------------------

  - name: approve-unknown-https
    description: Require approval for unknown HTTPS
    ports: [443]
    decision: approve
    message: "Agent wants to connect to: {{.RemoteAddr}}"
    timeout: 2m

  - name: approve-unknown-http
    description: Require approval for HTTP (insecure)
    ports: [80]
    decision: approve
    message: "Agent wants HTTP (insecure) to: {{.RemoteAddr}}"
    timeout: 2m

  - name: default-deny-network
    description: Deny all other network connections
    domains:
      - "*"
    decision: deny

# =============================================================================
# COMMAND RULES
# =============================================================================

command_rules:
  # ---------------------------------------------------------------------------
  # Allow curl/wget - network rules will block malicious domains
  # ---------------------------------------------------------------------------

  - name: allow-network-tools
    description: Allow curl/wget (network rules enforce domain policy)
    commands:
      - curl
      - wget
    decision: allow

  # ---------------------------------------------------------------------------
  # Allow safe commands
  # ---------------------------------------------------------------------------

  - name: allow-safe-commands
    description: Standard safe commands
    commands:
      - bash
      - sh
      - /bin/bash
      - /bin/sh
      - /usr/bin/bash
      - /usr/bin/sh
      - ls
      - cat
      - head
      - tail
      - grep
      - find
      - wc
      - sort
      - uniq
      - diff
      - pwd
      - echo
      - date
      - which
    decision: allow

  - name: allow-dev-tools
    description: Development tools
    commands:
      - git
      - node
      - npm
      - python
      - python3
      - pip
      - pip3
      - cargo
      - go
      - make
    decision: allow

  # ---------------------------------------------------------------------------
  # Approve package installation
  # ---------------------------------------------------------------------------

  - name: approve-package-install
    description: Require approval for package installation
    commands:
      - npm
      - pip
      - pip3
      - cargo
    args_patterns:
      - "install*"
      - "add*"
    decision: approve
    message: "Agent wants to install packages: {{.Args}}"

  # ---------------------------------------------------------------------------
  # Block dangerous commands
  # ---------------------------------------------------------------------------

  - name: block-rm-recursive
    description: Block recursive delete (AI hallucination protection)
    commands:
      - rm
    args_patterns:
      - "*-r*"
      - "*--recursive*"
      - "*-rf*"
      - "*-fr*"
    decision: deny
    message: "Recursive delete blocked. Files can be removed individually."

  - name: block-network-tools
    description: Block raw network tools (reverse shell prevention)
    commands:
      - nc
      - netcat
      - ncat
      - socat
      - telnet
      - ssh
      - scp
      - rsync
    decision: deny
    message: "Raw network tool blocked: {{.Command}}"

  - name: block-system-commands
    description: Block system administration commands
    commands:
      - shutdown
      - reboot
      - systemctl
      - service
      - mount
      - umount
      - dd
      - fdisk
      - mkfs
      - kill
      - killall
      - pkill
    decision: deny

  - name: block-container-escape
    description: Block container escape tools
    commands:
      - sudo
      - su
      - chroot
      - nsenter
      - unshare
      - docker
      - podman
      - nerdctl
    decision: deny
    message: "Container escape attempt blocked: {{.Command}}"

  # ---------------------------------------------------------------------------
  # Allow all other commands (security enforced via file/network rules)
  # ---------------------------------------------------------------------------

  - name: allow-other-commands
    description: Allow remaining commands
    commands:
      - "*"
    decision: allow

# =============================================================================
# RESOURCE LIMITS - Conservative for multi-tenant safety
# =============================================================================

resource_limits:
  max_memory_mb: 2048
  memory_swap_max_mb: 0
  cpu_quota_percent: 50
  pids_max: 100
  disk_read_bps_max: 52428800   # 50 MB/s
  disk_write_bps_max: 26214400  # 25 MB/s
  command_timeout: 5m
  session_timeout: 1h
  idle_timeout: 15m

# =============================================================================
# AUDIT SETTINGS - FULL LOGGING
# =============================================================================

audit:
  log_allowed: true
  log_denied: true
  log_approved: true
  include_stdout: true
  include_stderr: true
  include_file_content: false
  retention_days: 90
